language: python

os:
  - linux
  - osx

python:
  - "3.5"
  - "3.6"
  - "3.7"

dist: xenial
services:
  - xvfb

install:
  - pip install coveralls pyautogui pynput pillow img2pdf PyPDF2
    
script:
  - xvfb-run python test.py

after_success:
  - coveralls