language: python

os:
  - linux
  - osx

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install coveralls pyautogui pynput pillow img2pdf PyPDF2
    
script:
  - python test.py

after_success:
  - coveralls